---
name: Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: aj-welch
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run analysis
        run: nix develop --command task analyze:check:all
